name: Deploy Node.js Dockerized Service

on:
  push:
    branches: [ main ]  # deploy only when main is pushed

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'sudo mkdir -p /opt/nodejs-docker-service && sudo chown -R ubuntu:ubuntu /opt/nodejs-docker-service'

          rsync -avz --exclude '.git' --exclude 'node_modules' --exclude '.github' ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/opt/nodejs-docker-service/


      - name: Build and Run Docker container on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /opt/nodejs-docker-service
            docker build -t nodejs-docker-service .
            docker stop nodejs-docker-service || true
            docker rm nodejs-docker-service || true
            docker run -d --env-file .env -p 80:3000 --name nodejs-docker-service nodejs-docker-service
          EOF

